name: .NET API CI Pipeline

# Define quando a pipeline vai rodar
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        working-directory: ./ClyvoVet.Api
        run: dotnet restore

      - name: Compilar o projeto (Build)
        working-directory: ./ClyvoVet.Api
        run: dotnet build --no-restore --configuration Release
